name: "4. Generate README (Merged Rules Index)"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Links base ref (e.g. main or rules-YYYY-MM-DD). Default: main"
        required: false
        type: string
      cdn:
        description: "CDN for links: jsdelivr or raw"
        required: false
        default: "jsdelivr"
        type: choice
        options:
          - "jsdelivr"
          - "raw"
  workflow_run:
    # 同时监听工作流名称与文件路径，避免改名或大小写差异导致不触发
    workflows:
      - "5. Merge Rule Sets (Type Check + Organize)"
      - ".github/workflows/merge-rules.yml"
    types: [completed]

permissions:
  contents: write

concurrency:
  group: gen-readme
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  gen-readme:
    runs-on: ubuntu-latest
    # 仅在前置 workflow_run 成功时继续执行；手动触发不受此限制
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository (full history for rebase)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        shell: bash
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'

      - name: Rebase to latest main
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="${GITHUB_REF_NAME:-main}"
          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git pull --rebase origin "$BRANCH"

      - name: Make generator executable
        shell: bash
        run: chmod +x scripts/gen-readme.sh

      - name: Generate README (merged-rules only)
        shell: bash
        env:
          INPUT_REF: ${{ inputs.ref || 'main' }}
          INPUT_CDN: ${{ inputs.cdn || 'jsdelivr' }}
        run: scripts/gen-readme.sh

      - name: Commit README changes (if any)
        id: commit
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet README.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No README changes."
            exit 0
          fi
          git add README.md
          git commit -m "docs(readme): auto-update (merged-rules) at $(date +'%Y-%m-%d %H:%M:%S %Z')"
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Push with rebase retry
        if: steps.commit.outputs.changed == 'true'
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="${GITHUB_REF_NAME:-main}"
          if git push origin "$BRANCH"; then
            exit 0
          fi
          echo "Non-fast-forward, rebasing and retrying..."
          git pull --rebase origin "$BRANCH"
          git push origin "$BRANCH" || {
            echo "::error::Failed to push after rebase retry."
            exit 1
          }
