name: "4. Generate README (Merged Rules Index)"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Links base ref (e.g. main or rules-YYYY-MM-DD). Default: main"
        required: false
        type: string
      cdn:
        description: "CDN for links: jsdelivr or raw"
        required: false
        default: "jsdelivr"
        type: choice
        options:
          - "jsdelivr"
          - "raw"
  workflow_run:
    workflows: ["5. Merge Rule Sets (Smart Copy)"]
    types: [completed]
    branches: [main]
  push:
    branches: [ main ]
    paths:
      - "merged-rules/**"
      - "scripts/gen-readme.sh"

permissions:
  contents: write

concurrency:
  group: gen-readme
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  gen-readme:
    runs-on: ubuntu-latest
    # 只在前置工作流成功时运行（如果是 workflow_run 触发）
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make generator executable
        shell: bash
        run: chmod +x scripts/gen-readme.sh

      - name: Generate README (merged-rules only)
        shell: bash
        env:
          INPUT_REF: ${{ inputs.ref || 'main' }}
          INPUT_CDN: ${{ inputs.cdn || 'jsdelivr' }}
        run: scripts/gen-readme.sh
