name: "5. Merge Rule Sets (Smart Copy)"

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Merge config file (default: merge-config.yaml)"
        required: false
        type: string
        default: "merge-config.yaml"
  push:
    branches: [ main ]
    paths:
      - "rulesets/**"
      - "merge-config.yaml"
      - "scripts/merge-rules.sh"

permissions:
  contents: write

concurrency:
  group: merge-rules
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  merge-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make merge script executable
        shell: bash
        run: chmod +x scripts/merge-rules.sh

      - name: Run merge script
        shell: bash
        env:
          CONFIG_FILE: ${{ inputs.config_file || 'merge-config.yaml' }}
        run: ./scripts/merge-rules.sh
