name: "5. Merge Rule Sets (Smart Copy)"

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Merge config file (default: merge-config.yaml)"
        required: false
        type: string
        default: "merge-config.yaml"
  push:
    branches: [ main ]
    paths:
      - "rulesets/**"
      - "merge-config.yaml"
      - "scripts/merge-rules.sh"

permissions:
  contents: write
  actions: write   # 新增：允许本工作流触发 gen-readme.yml 的 workflow_dispatch

concurrency:
  group: merge-rules
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  merge-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make merge script executable
        shell: bash
        run: chmod +x scripts/merge-rules.sh

      - name: Run merge script
        shell: bash
        env:
          CONFIG_FILE: ${{ inputs.config_file || 'merge-config.yaml' }}
        run: ./scripts/merge-rules.sh

      # 新增：合并成功后触发 gen-readme.yml（要求该工作流包含 on: workflow_dispatch）
      - name: Trigger gen-readme.yml
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          WORKFLOW_FILE: gen-readme.yml
          REF: ${{ github.ref_name || 'main' }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Dispatching ${WORKFLOW_FILE} on ${REPO}@${REF} ..."
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW_FILE}/dispatches" \
            -d "{\"ref\":\"${REF}\",\"inputs\":{\"ref\":\"${REF}\"}}"
          echo "Dispatched gen-readme."
