name: "5. Merge Rule Sets (Smart Copy)"

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Merge config file (default: merge-config.yaml)"
        required: false
        type: string
        default: "merge-config.yaml"
  workflow_run:
    workflows: ["1. Daily Sync and Sanitize Rules (mihomo-core)"]
    types: [completed]
    branches: [main]
  push:
    branches: [ main ]
    paths:
      - "rulesets/**"
      - "merge-config.yaml"
      - "scripts/merge-rules.sh"

permissions:
  contents: write
  actions: write  # 需要触发其他工作流

concurrency:
  group: merge-rules
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  merge-rules:
    runs-on: ubuntu-latest
    # 只在前置工作流成功时运行（如果是 workflow_run 触发）
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        shell: bash
        run: chmod +x scripts/merge-rules.sh

      - name: Run smart merge
        shell: bash
        env:
          CONFIG_FILE: ${{ inputs.config_file || 'merge-config.yaml' }}
        run: scripts/merge-rules.sh

      # 触发下一个工作流：gen-readme
      - name: Trigger gen-readme workflow
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo "Triggering gen-readme workflow..."
          gh workflow run "gen-readme.yml" --ref main
