name: "1. Daily Sync and Sanitize Rules (mihomo-core)"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # 北京时间 05:00

permissions:
  contents: write
  actions: write  # 需要触发其他工作流

concurrency:
  group: sync-rules
  cancel-in-progress: true

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make sync script executable
        shell: bash
        run: chmod +x scripts/sync.sh

      - name: Run sync script
        shell: bash
        env:
          STRICT: "false"   # 任一源失败就终止可改 "true"
        run: scripts/sync.sh

      # 触发下一个工作流：merge-rules
      - name: Trigger merge-rules workflow
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo "Triggering merge-rules workflow..."
          gh workflow run "merge-rules.yml" --ref main
